name: Matthew Mayer
favicon: null
layout_spectrum: 0.9502344082575291
typography_spectrum: 0.68821
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#36312b'
    - '#dedede'
    - '#bbbab8'
    - '#6d6862'
  brandStrength: 0.3902078033424914
  lightness: 0.23025761311873794
  saturation: 0.5607430194504559
  rhythmicContrast: 0.28314120159484446
purpose: []
