name: Matthew Mayer
favicon: null
layout_spectrum: 0.9502344082575291
typography_spectrum: 0.5261487185489386
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3902078033424914
  lightness: 0.23025761311873794
  saturation: 0.5607430194504559
  rhythmicContrast: 0.28314120159484446
purpose: []
